apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.openshift.io/v1alpha1",
          "kind": "ExternalSecrets",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "external-secrets-operator"
            },
            "name": "cluster"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-06T10:30:33Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: external-secrets-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: |-
        ExternalSecrets describes configuration and information about the managed external-secrets
        deployment. The name must be `cluster` to make ExternalSecrets a singleton that is, to
        allow only one instance of ExternalSecrets per cluster.

        When an ExternalSecrets is created, a new deployment is created which manages the
        external-secrets and keeps it in the desired state.
      displayName: ExternalSecrets
      kind: ExternalSecrets
      name: externalsecrets.operator.openshift.io
      version: v1alpha1
    - kind: ExternalSecretsOperator
      name: externalsecretsoperators.operator.openshift.io
      version: v1alpha1
  description: external secrets operator for Red Hat OpenShift deploys and manages
    `external-secrets` application in OpenShift clusters. `external-secrets` provides
    an uniformed interface to fetch secrets stored in external providers like  AWS
    Secrets Manager, HashiCorp Vault, Google Secrets Manager, Azure Key Vault, IBM
    Cloud Secrets Manager to name a few, stores them as secrets in OpenShift. It provides
    APIs to define authentication and the details of the secret to fetch.
  displayName: external secrets operator for Red Hat OpenShift
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - operator.openshift.io
          resources:
          - externalsecrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.openshift.io
          resources:
          - externalsecrets/finalizers
          verbs:
          - update
        - apiGroups:
          - operator.openshift.io
          resources:
          - externalsecrets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: external-secrets-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: external-secrets-operator
          control-plane: controller-manager
        name: external-secrets-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /external-secrets-operator
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: external-secrets-operator-controller-manager
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - secrets
  - external-secrets
  - external-secrets-operator
  links:
  - name: External Secrets Operator
    url: https://external-secrets-operator.domain
  maintainers:
  - email: tgeer@redhat.com
    name: Trilok Geer
  - email: bhb@redhat.com
    name: Bharath B
  - email: swghosh@redhat.com
    name: Swarup Ghosh
  - email: sbhor@redhat.com
    name: Siddhi Bhor
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.1.0
