apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: external-secrets-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: |-
        ExternalSecrets describes configuration and information about the managed external-secrets
        deployment. The name must be `cluster` to make ExternalSecrets a singleton that is, to
        allow only one instance of ExternalSecrets per cluster.

        When an ExternalSecrets is created, a new deployment is created which manages the
        external-secrets and keeps it in the desired state.
      displayName: ExternalSecrets
      kind: ExternalSecrets
      name: externalsecrets.operator.openshift.io
      version: v1alpha1
  description: external secrets operator for Red Hat OpenShift deploys and manages
    `external-secrets` application in OpenShift clusters. `external-secrets` provides
    an uniformed interface to fetch secrets stored in external providers like  AWS
    Secrets Manager, HashiCorp Vault, Google Secrets Manager, Azure Key Vault, IBM
    Cloud Secrets Manager to name a few, stores them as secrets in OpenShift. It provides
    APIs to define authentication and the details of the secret to fetch.
  displayName: external secrets operator for Red Hat OpenShift
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - secrets
  - external-secrets
  - external-secrets-operator
  links:
  - name: External Secrets Operator
    url: https://external-secrets-operator.domain
  maintainers:
  - email: tgeer@redhat.com
    name: Trilok Geer
  - email: bhb@redhat.com
    name: Bharath B
  - email: swghosh@redhat.com
    name: Swarup Ghosh
  - email: sbhor@redhat.com
    name: Siddhi Bhor
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.0.0
