---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-sdk-server
  labels:
    app.kubernetes.io/name: bitwarden-sdk-server
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.3.1"
    app.kubernetes.io/managed-by: external-secrets-operator
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: bitwarden-sdk-server
    app.kubernetes.io/instance: external-secrets
